spring.application.name=mcpratapp
spring.datasource.url=jdbc:postgresql://localhost:5432/mcprata
spring.datasource.username=zambrin
spring.datasource.password=zambrin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000
app.cors.allowed-origins=http://localhost:5173