spring.application.name=mcpratapp
spring.datasource.url=jdbc:postgresql://localhost:5432/mcprata
spring.datasource.username=zambrin
spring.datasource.password=zambrin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
app.jwt.secret=qwibdqiyhdwgqiydg917g2iu1bdkj1bd1id2891ud1092d12hdhd19dh2190
app.jwt.expiration=900000
app.jwt.refresh-expiration=604800000
app.cors.allowed-origins=http://localhost:5173